### ISSUE TITLE
Better syntax higlighting and ligature font support

### ISSUE THREAD

**Issue by ekickx** [ekickx/personal-blog#8]
# Goal
- Code in `<pre>` and `<code>` support ligature
- Show line numbering on `<pre>` as default
- Syntax for command line

# TODO
- [x] Set `Victor Mono` as font-mono (ligature font)
- [x] Show line numbering
  - [x] Set `alwaysWrapLineHighlights` as `true`
  - [x] Css for line number style
- [ ] Syntax for command line
